- src/common/Prop.js
For now, when we apply changes to a property on its change, we only consider authored properties. If I get the logic correctly, when `change.source` equals `default`, we should use the default value (from the prop spec) if it is provided.
@LeaVerou, could you please take a look at the proposed change? Do I get the logic correctly, or does this fix the `<channel-slider>` component by accident? 😅
> Take default values into account

- src/color-picker/color-picker.js
- When the component is mounted, we must dispatch the `input` event to update the corresponding color swatch.
- Previously, for the `color` prop, we used the corresponding spec from the `<channel-slider>`. But it depends on the `channel` property `<color-picker>` doesn't have. I'm sure the solution I suggest is not optimal at all. I just needed something to make the picker work.
> First pass on fixing <color-picker>

- src/common/defineEvents.js
Fixes the check whether `oneventname` is implemented in a class.
> Fix typo in `defineEvent()`

- src/color-slider/color-slider.js
We no longer need to fire the `input` event on initialization—everything is handled automatically by `valuechange`/`colorchange` event listeners.
This makes the `#initialized` property redundant and fixes the weirdness when the sider has two private `#initialized` properties (one inherited from the `NudeElement` class).
> Remove no longer necessary code

- src/color-swatch/README.md
- src/color-swatch/color-swatch.js
Related to #36 
Not working. Need to debug why.
> First stab at oncolorchange for `<color-swatch>`

- src/color-slider/color-slider.css
For some reason, the `&::-webkit-slider-thumb:active` rule doesn't work.
> [color-slider] Fix active style in WebKit-based browsers

- src/color-picker/color-picker.js
This also includes the default `space`. That's why we no longer need to render `<color-picker>` after the component is connected.
This also solves the issue with setting `space` programmatically—with this PR merged, it'll work as expected.
> [color-picker] Render the component on every change of `space`

- src/channel-slider/README.md
I'm unsure whether I correctly described the exposed part of `<color-slider>`. Should we document `exportparts`?
> [channel-slider] Add info about slots and parts to the docs

- src/color-slider/color-slider.js
Previously, if specified on `<color-slider>`, they all became equal to the slider value, not the corresponding prop's value.
This PR fixes it.
> [color-slider] Fix the spinner `min`, `max`, and `step` values

- src/color-picker/color-picker.js
- Get rid of `render()`—all the changes are handled with `handleEvent()` and `propChangedCallback()`
- When `space` is set, we should update `color` (if it was previously set) accordingly
- `<color-swatch>` doesn't have the `color` attribute, so when the `<color-picker>`'s `color` prop changes, we should propagate changes to the swatch, and update its property, not the attribute
**Note:** Until #85 is fixed, we might face issued with the swatch (like #84).
> [color-picker] Fix issues

- src/gamut-badge/gamut-badge.js
In the dependency graph, the order of props also matters—`gamuts` should be updated before `color`.
> [color-swatch] Update the corresponding custom CSS properties on the `gamuts` change, fixes #79

- src/color-slider/color-slider.js
> [color-slider] Correctly handle spinner properties when showing progress

- src/color-scale/color-scale.js
- src/color-swatch/color-swatch.css
- src/color-swatch/color-swatch.js
It's a very basic implementation, so we could have something to start with. 🙂
It looks like this:
When defining the type of `coords`, I used a workaround because of [the issue](https://github.com/nudeui/element/issues/27) I faced.
I wonder whether we should do something like `+(value).toPrecision(4)` to make the output look nicer (or is it OK to see that many digits?). Is there a way to specify precision in `Color.js` we could use?
**UPDATE**
Here is the code that produces the image above:
```html
<color-swatch coords="oklch.l, oklch.c, oklch.h" size="large">oklch(80% 50% 70)</color-swatch>
<div id="future_swatch_container"></div>
<script>
let swatch = document.createElement("color-swatch");
swatch.color = "oklch(65% 0.15 210)";
swatch.setAttribute("size", "large");
swatch.textContent = …
```
> [color-swatch][color-scale] First stab at implementing the coords prop

- src/color-picker/color-picker.js
These changes were gone for some reason, even though [we merged the corresponding PR yesterday](https://github.com/color-js/elements/pull/91).
I'm going to merge this PR to restore the lost changes.
> [color-picker] If no color is provided, use the default one (#91)

- src/color-chart/color-chart-global.css
- src/color-chart/color-chart.css
- Chart containers should have a `display` type respecting height
- Their height should be specified explicitly: `clamp()` works if `0`, as the minimum value, has units; `aspect-ratio` also works
- The previous steps allow container query units (`cqw`, `cqh`) to work as they should
> [color-charts] Fix issues with containers

- src/color-chart/color-chart-global.css
For now, when we hover a line between two points, the tooltip for the left one is shown (even when we are close enough to the right point of the two):
To my mind (and expectations), we should only show tooltips on points hover. This PR should fix it.
> [color-chart] Don't show points tooltips on hovering the line

- src/color-chart/color-chart.css
Otherwise, the `cqh` CQ unit doesn't work, which leads to the wrong placement of data points on the chart.
> Change the chart container type

- src/color-chart/color-chart-global.css
Authors can hide it at any time by adding this rule to their style sheet:
`color-scale::part(info) { display: none; }`
> Show the swatch info if one is provided

- src/color-chart/color-chart.js
- src/color-scale/color-scale.js
- src/color-swatch/color-swatch.js
Changes:
1. `<color-swatch>` — Update color info on every color change
2. `<color-scale>` — Expose the `colorschange` event
3. `<color-chart>` — Handle the `colorschange` event from the underlying color scales
4. `<color-chart>` — On the colors set, make sure the last swatch is not connected to the non-existent next swatch
Do we need to propagate the `colorschange` event so that it can be listened to on `<color-chart>`?
> First stub on making charts reactive

- src/color-chart/README.md
- src/color-chart/color-chart.js
Demo: https://deploy-preview-116--color-elements.netlify.app/src/color-chart/#the-info-attribute
> [color-chart] Add support for the `info` prop

- src/color-swatch/color-swatch.js
As we discussed in #96, the color info is also helpful to get programmatically. This PR addresses this. Under the hood, [the data structure suggested by @LeaVerou (Option 1)](https://github.com/color-js/elements/pull/96#issuecomment-2173355441) is used.
This PR is the first step to implementing deltas and contrast and is intended to check if I got the main idea shaped in the PR mentioned right. The existing API is the same, so it's not a breaking change. Everything still works as before.
The gist of what this PR introduces can be seen in the screenshot (`<color-swatch>` is a Lego block for color charts):
> [color-swatch] Add the `colorInfo` prop

- src/color-chart/README.md
- src/color-chart/color-chart.js
The main idea behind the fix is that we are not interested in using _any_ number on the default label as the X-coord. Such a number _must_ be specified as a coord: either it's the only number in the color label or detached from the previous text with a space.
Live preview: https://deploy-preview-133--color-elements.netlify.app/src/color-chart/
> [color-chart] Correctly plot colors without labels, fixes #103

- assets/js/index.js
Remove the `scroll` event listener (it came from the Color.js website, where we now use [a different approach to position the menu](https://github.com/color-js/color.js/commit/a078a420480107d0e948030ab8264944ba8d0ecc)).
> Make the website more performant

- README.md
- src/space-picker/README.md
- src/space-picker/space-picker.css
- src/space-picker/space-picker.js
Partially addresses #123.
```html
<space-picker></space-picker>
```
```html
<space-picker value="oklab"></space-picker>
```
```html
<space-picker spaces="oklch, p3, srgb"></space-picker>
```
```html
<space-picker spaces="oklch, p3, srgb" value="p3"></space-picker>
```
```html
<space-picker onspacechange="this.nextElementSibling.textContent = this.value"></space-picker>
<output></output>
```
> [space-picker] First iteration

- src/gamut-badge/gamut-badge.css
See https://lea.verou.me/blog/2024/contrast-color/
Text on the badges is now readable:
> [gamut-badge] Use contrast text color

- README.md
- src/channel-picker/README.md
- src/channel-picker/channel-picker.css
- src/channel-picker/channel-picker.js
- src/space-picker/space-picker.css
Partially addresses #124.
It's a bare minimum, just for a start.
Docs: https://deploy-preview-147--color-elements.netlify.app/src/channel-picker/
> [channel-picker] First iteration

- src/channel-picker/channel-picker.js
Preview: https://deploy-preview-149--color-elements.netlify.app/src/channel-picker/
> [channel-picker] Preserve previously selected channel

- src/channel-slider/channel-slider.css
- src/channel-slider/channel-slider.js
- The channel range is moved to the right (to the channel label) and is hidden until the slider is hovered or some of its components have focus.
- The current slider value is at the right part of the slider label and is dimmed until the slider is hovered or the value is focused. The tooltip is removed (or do we need to have it too?)
It looks like this:
In the context of `<color-picker>`, it looks like this:
One thing that bothers me is that the spin buttons are outside of the slider (if we want the value is aligned to the right of the slider):
Or is it worth applying `&::-webkit-textfield-decoration-container { flex-flow: row-reverse; }` to place the spin buttons to the left of the number? I'm afraid it might confuse users, though. But I'm not sure.
Or simply don't align the value to the …
> [channel-slider] First stab at working on #154

- src/channel-slider/channel-slider.css
But make them subtly until the user interacts with them.
**Not focused (hovered)**
**Focused**
Unfortunately, we are a bit tight with options here (except lowering `opacity` or applying filters, as far as I'm aware). But from my perspective, filters are a bit too much in this case.
> [channel-slider] Show the spin buttons all the time

- src/color-swatch/README.md
- src/color-swatch/color-swatch.js
#107 seems to be a blocking issue for #167, so let's try to address it first.
This PR adds the `label` prop to `<color-swatch>` and the corresponding part for custom styling. As @LeaVerou suggested in #107, the implementation is inspired by the `<option>` element.
There is no separate slot for the value of this attribute because I couldn't think of any use cases where it might be needed (I might miss something, though).
Live preview: https://deploy-preview-171--color-elements.netlify.app/src/color-swatch/#the-label-attribute
> [color-swatch] Add support for the `label` prop, closes #107

- src/channel-slider/README.md
- src/channel-slider/channel-slider.js
It works in every version of Color.js. It's a spin-off of #63 to simplify the process of adding new features.
Preview: https://deploy-preview-173--color-elements.netlify.app/src/channel-slider/
> [channel-slider] Add support for the `alpha` channel

- src/color-picker/README.md
- src/color-picker/color-picker.js
Related to #173 (and should be merged after it). Works with all versions of Color.js
Docs: https://deploy-preview-174--color-elements.netlify.app/src/color-picker/#the-alpha-attribute
> [color-picker] Add support for `alpha`, closes #57

- src/space-picker/README.md
- src/space-picker/space-picker.js
To handle custom color space labels.
Live preview: https://deploy-preview-172--color-elements.netlify.app/src/space-picker/#custom-labels
> [space-picker] Add the `getSpaceLabel()` prop

- src/color-chart/README.md
- src/color-chart/color-chart.css
- src/color-chart/color-chart.js
We need to tweak styles here depending on what base style of `<channel-picker>` we choose (we might end up with this: #169). So, it's only the first step. The implemented logic will be the same regardless.
Live preview: https://deploy-preview-170--color-elements.netlify.app/src/color-chart/
> [color-chart] First step in `<channel-picker>` integration

- _includes/component.njk
- assets/js/index.js
Closes #19. Closes #20.
Reuses the code from the Color.js website by maximum:
**Narrow page:**
> [website] Add sidebar with all elements and in-page sections

- src/color-scale/color-scale.css
- src/color-scale/color-scale.js
- src/color-swatch/color-swatch.css
- src/color-swatch/color-swatch.js
Also, on small devices.
This fix was part of [another PR](#167), but since we don't want it to be held, I extracted it to this one.
~~This fix allows [color palettes](https://palettes.colorjs.io/palettes/) to look a bit better:~~
~~However, not all the issues can be fixed. For example, [Subgrid doesn't play well with CQ](https://codepen.io/dmitrysharabin/pen/oNRZzbb) in all (🫣) browsers! That's why we can't get (at least) something like this by merging this PR:~~
I'll try to improve this further, but I just want to ensure we have something to start with.
**UPDATE**
I've come up with another approach I like more: We can apply `text-overflow: ellipsis` to swatch labels on overflow (the full label text can be seen in a tooltip on hover, thanks to the `title` attribute).
We also expose it as …
> [color-swatch][color-scale] Fix layout issues when there are many color swatches

- src/common/color-element.js
This is such a performance gain! Even quite heavy color palettes site feels more responsive with this tiny fix. Your proposal, @LeaVerou, worked (I had no doubts that it would). Thank you!
However, we need to release the NudeElement and use it in color elements to see all these gains. I ran all my tests using the dev versions of all our packages.
> [color-elements] Use `<link>` for shadow styles instead of `@import()`

- src/color-swatch/color-swatch.css
Specifically when used inside `<color-scale>`s. Fixes the issue with swatches' inline size on the [Research on color palettes website](https://palettes.colorjs.io/).
> [color-swatch] Avoid overflow

- src/color-swatch/color-swatch.css
For now, they are not shown on hover.
> [color-swatch] Fix the details part's compact styles in Safari
